theme: jekyll-theme-cayman
title: RandomCollection
description: RandomCollection offers small articles about economics, finance, and statistics. In addition, a strong focus is put on coding techniques used to enable corresponding analyses, especially Python and SQL. There is also a section about HTML. 
